services:
  postgres:
    image: postgres:16-alpine
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=secret
      - POSTGRES_DB=q-q-tem-pra-hj-db
    ports:
      - '6432:5432'
    volumes:
      - postgres-data:/var/lib/postgresql/data
  app:
    build: .
    ports:
      - '8080:8080'
    depends_on:
      - postgres
    environment:
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_USER=user
      - DB_PASSWORD=secret
      - DB_NAME=q-q-tem-pra-hj-db
volumes:
  postgres-data:
    driver: local
