INSERT INTO recipes (name) VALUES
    ('Quibe'),
    ('Berinjela à parmegiana'),
    ('Panqueca e recheios'),
    ('Torta de palmito'),
    ('Moqueca de palmito'),
    ('Rondelli de abobrinha'),
    ('Panqueca de espinafre'),
    ('Torta queijo e cebola caramelizada'),
    ('Hambúrguer de grão de bico'),
    ('Bolinho de espinafre'),
    ('Almôndegas'),
    ('Gnocchi de ricotta a la Mariah'),
    ('Tropeiro'),
    ('Lentilha laranja'),
    ('Ovo com ragu de cogumelos'),
    ('Bolinho de queijo de cabra'),
    ('Yakisoba legumes'),
    ('Risoto alho poro'),
    ('Torta de abóbrinha'),
    ('Bife da Vovó Neusa'),
    ('Panqueca de repolho'),
    ('Quiche manjericao +tomate'),
    ('Bolo salgado'),
    ('Mjadra'),
    ('Couve-flor; gratinada'),
    ('Feijoada'),
    ('Medalhão'),
    ('Strogonoff cogu/carne'),
    ('Carbonara'),
    ('Lasanha'),
    ('Suflê de queijo prático'),
    ('Arroz piamontese');
